### PR TITLE
Update 2.3

### PR DESCRIPTION
**Pull request by rainbowwarmth**

### CODE REVIEW

**Comment by hashblen** [comment]
I found [https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip](https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip) though, that is a bit outdated :)

**Comment by rainbowwarmth** [comment]
> 不过[，我发现 https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip](https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip)，这有点过时:)

This PR does not add a test service link. If you want to add a PR, please do it yourself.

**Comment by rainbowwarmth** [comment]
> I found https://autopatchos.starrails.com/client/Beta/20240614195024_Wa3GBOJIRMB94tXB/StarRail_2.3.51.zip though, that is a bit outdated :)

This PR does not add a test service link. If you want to add a PR, please do it yourself.

**Comment by hashblen** [comment]
Sorry for bothering, I misread :)

**Pull request closed without merging**
