### PR TITLE
BETA 2.1.53 & 54 & 55

### PR DESCRIPTION
**Pull request by 360NENZ**
From GuraLeak

### CODE REVIEW

**Comment by Nazir78** [comment]
Can You Provide Android Beta As Well?

**Comment by 360NENZ** [comment]
> Can You Provide Android Beta As Well?

Added

**Comment by Nazir78** [comment]
Is There Any OSBeta Available For Android(Not CN)

**Comment by 360NENZ** [comment]
OS Android BETA uses Google Play, no download link (just like iOS BETA uses TestFlight)

**Comment by Nazir78** [comment]
How to play cn beta ? It needs cn account, is There any test account available?

**Comment by 360NENZ** [comment]
Join Telegram [Zenith](https://t.me/ZenithMHY) to play CN BETA

> How to play cn beta ? It needs cn account, is There any test account available?

**Comment by Nazir78** [comment]
Thank you very much

**Pull request merged**
